### ISSUE TITLE
No compatible devices found

### ISSUE THREAD

**Issue by GabeConsalter** [manualmanul/Annemone#1]
Hey.
I'm excited about this project.

For now, when I run `annemone single 255 0 255` returns **No compatible devices found**.

My AnnePro 2 is connected by USB cable.

My environment:
![image](https://user-images.githubusercontent.com/6640360/83029369-fe9b6200-a008-11ea-8b54-f8f0246cff5a.png)

**Comment by manualmanul** [comment]
Hello! Thank you for bringing this to my attention, I haven't tested annemone on Linux yet. 

Could you please run the following commands and let me know what the output is? This will output a list of USB devices connected to your computer, feel free to remove entries that aren't the keyboard.

```shell
npm install -g node-hid
hid-showdevices
```

**Comment by GabeConsalter** [comment]
```bash
devices: [ { vendorId: 1241,
    productId: 32777,
    path: '/dev/hidraw6',
    serialNumber: 'SN0000000001',
    manufacturer: 'OBINLB',
    product: 'USB-HID Keyboard',
    release: 256,
    interface: 0 },
  { vendorId: 1241,
    productId: 32777,
    path: '/dev/hidraw7',
    serialNumber: 'SN0000000001',
    manufacturer: 'OBINLB',
    product: 'USB-HID Keyboard',
    release: 256,
    interface: 1 },
  { vendorId: 1241,
    productId: 32777,
    path: '/dev/hidraw8',
    serialNumber: 'SN0000000001',
    manufacturer: 'OBINLB',
    product: 'USB-HID Keyboard',
    release: 256,
    interface: 2 },
  { vendorId: 1241,
    productId: 32777,
    path: '/dev/hidraw9',
    serialNumber: 'SN0000000001',
    manufacturer: 'OBINLB',
    product: 'USB-HID Keyboard',
    release: 256,
    interface: 3 },
# ...
```

**Comment by manualmanul** [comment]
Interesting, the product ID is different from my Anne Pro 2. I've updated annemone to detect this variant of the keyboard, please run `npm update -g annemone` and if the error still occurs, reopen this ticket.

**Comment by GabeConsalter** [comment]
Now, it works like a charm.

Thank you @manualmanul.
