### ISSUE TITLE
TypeError: arrayOfRgbValues.flat is not a function

### ISSUE THREAD

**Issue by JcdeA** [manualmanul/Annemone#6]
When I try to run `LEDController.setIndividualKeys({f:[255,255,0]})`, it gives a `TypeError: arrayOfRgbValues.flat is not a function`. How can I fix this?

**Comment by manualmanul** [comment]
Can you please check that your Node version is v12.x or newer?

**Comment by JcdeA** [comment]
Oops. looks like I have `v10.20.1`. I'll try again after upgrading.

**Comment by JcdeA** [comment]
Yep. That was the issue. I'm new to node.js, Thank you for helping me!

**Comment by manualmanul** [comment]
No problem, glad I could help!
