### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by JcdeA** [manualmanul/Annemone#7]
I don't really know where I should post this, so I'm posting here.
This is a pretty useful project, but I feel like the name should be something that tells more about what it is. like `annepro2-nodejs` or something like that. It doesn't show up in search engines.

Thank you.

**Comment by manualmanul** [comment]
You're not wrong, I haven't done much SEO optimization for this project. However, I don't want to rename this project to something generic, so instead I'll create a webpage for it and add a GitHub description field. I think this should be a good solution to make this project more discoverable.

Thank you for the suggestion though!
